name: Deploy Slash Commands

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: pnpm/action-setup@v4
      with:
        version: latest
        run_install: false
    - uses: actions/setup-node@v6
      with:
        node-version: '24'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Deploy command
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
      run: pnpm run deploy-commands